# This is an example configuration file.
# Copy this file to config.yaml and fill in your actual data.

# Global settings for the script
settings:
  # Interval between checks in minutes
  check_interval_minutes: 10

  # The root directory where series should be downloaded
  download_directory: "downloads"

  # Number of download retries for each episode
  download_retries: 3

  # Delay between download retries in seconds
  download_retry_delay: 5
  
  # Custom arguments for yt-dlp
  # Example for multi-threaded downloading:
  yt-dlp_args:
    - "--concurrent-fragments"
    - "4"
    # - "--limit-rate"
    # - "10M"

# List of series to track
series:
  - name: "Name of the Series"
    url: "https://filecrypt.cc/Container/YOUR_CONTAINER_ID.html"
    series: 0 # The number of the last episode you have downloaded.
  
  - name: "Another Series"
    url: "https://filecrypt.cc/Container/ANOTHER_ID.html"
    series: 5 # Starts checking for episodes 6 and newer.
